name: Lint & Typecheck

on:
  workflow_call:

jobs:
  lint-check:
    name: Lint & Typecheck
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.1.2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Lint JavaScript
        run: bun run lint

      - name: Lint CSS
        run: bun run lint:css

      - name: Lint HTML
        run: bun run lint:html

      - name: Typecheck
        run: bun run check

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v22.0.0

      - name: Lint GitHub Actions
        uses: reviewdog/action-actionlint@v1.69.1
